[#60][Fix] fix MSVC build error
Here the output, if this is not fixed:

C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(76): error C2440: '=': cannot convert from 'const vk::Instance' to 'VkInstance'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(76): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(77): error C2440: '=': cannot convert from 'const vk::PhysicalDevice' to 'VkPhysicalDevice'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(77): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(78): error C2440: '=': cannot convert from 'const vk::Device' to 'VkDevice'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(78): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(80): error C2440: '=': cannot convert from 'const vk::Queue' to 'VkQueue'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(80): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(81): error C2440: '=': cannot convert from 'nullptr' to 'VkPipelineCache'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(81): note: A native nullptr can only be converted to bool or, using reinterpret_cast, to an integral type
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(82): error C2440: '=': cannot convert from 'vk::DescriptorPool' to 'VkDescriptorPool'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(82): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(140): error C2664: 'bool ImGui_ImplVulkan_Init(ImGui_ImplVulkan_InitInfo *,VkRenderPass)': cannot convert argument 2 from 'vk::RenderPass' to 'VkRenderPass'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(140): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\lib\imgui/backends/imgui_impl_vulkan.h(65): note: see declaration of 'ImGui_ImplVulkan_Init'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(145): error C2664: 'bool ImGui_ImplVulkan_CreateFontsTexture(VkCommandBuffer)': cannot convert argument 1 from 'const vk::CommandBuffer' to 'VkCommandBuffer'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(145): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\lib\imgui/backends/imgui_impl_vulkan.h(69): note: see declaration of 'ImGui_ImplVulkan_CreateFontsTexture'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(233): error C2664: 'void ImGui_ImplVulkan_RenderDrawData(ImDrawData *,VkCommandBuffer,VkPipeline)': cannot convert argument 2 from 'const vk::CommandBuffer' to 'VkCommandBuffer'
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\src\vkcv\gui\GUI.cpp(233): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\Vayuni\workspace\git\cg-fp_vulkan\vkcv-framework\modules\gui\lib\imgui/backends/imgui_impl_vulkan.h(68): note: see declaration of 'ImGui_ImplVulkan_RenderDrawData'
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.299\bin\Hostx86\x86\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.